// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnqrvkvzjmmybtkkkdoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ucXJ2a3Z6am1teWJ0a2trZG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTczMTksImV4cCI6MjA3MTI5MzMxOX0.XrfcRopY7Pdlp4fCWerieqyTW2gm5MOuqbF1vko4nac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});